let companies=[
  {
    "Name":"Microsoft",
    "Bid":1,
     "Hiring":"May-Jun",
     "Package":"40LPA+",
     "Difficulty":"Medium",
     "Link":"https://careers.microsoft.com/us/en/search-results?category=Software%20Engineering",
  },
  {
    "Name":"Adobe",
    "Bid":1,
     "Hiring":"November",
     "Package":"39LPA+",
     "Difficulty":"Medium",
     "Link":"https://careers.adobe.com/us/en",
  },
  {
    "Name":"Ajio",
    "Bid":2,
     "Hiring":"November",
     "Package":"10-15LPA",
     "Difficulty":"Medium",
     "Link":"https://rcareers.ril.com/sap/bc/bsp/sap/zerec_home_page/home_page.do",
  },
  {
    "Name":"PharmEasy",
    "Bid":2,
     "Hiring":"November",
     "Package":"10-18LPA",
     "Difficulty":"Medium",
     "Link":"https://pharmeasy.in/careers/jobs/",
  },
  {
    "Name":"UrbanCompany",
    "Bid":2,
     "Hiring":"Jan-April",
     "Package":"25-30LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.urbancompany.com/jobs",
  },
  {
    "Name":"Meesho",
    "Bid":2,
     "Hiring":"November",
     "Package":"25-30LPA",
     "Difficulty":"Medium",
     "Link":"https://www.meesho.io/jobs",
  },
  {
    "Name":"Razor Pay",
    "Bid":3,
     "Hiring":"November",
     "Package":"15-18LPA",
     "Difficulty":"Medium",
     "Link":"https://razorpay.com/jobs/jobs-all/",
  },
  {
    "Name":"Zeta",
    "Bid":3,
     "Hiring":"Oct-Dec(Intern)",
     "Package":"15-28LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.zeta.tech/work-with-us/?department=AllDepartments",
  },
  {
    "Name":"Phone Pe",
    "Bid":3,
     "Hiring":"January",
     "Package":"38LPA",
     "Difficulty":"Medium",
     "Link":"https://www.phonepe.com/careers/jobs-by-department/engineering/",
  },
  {
    "Name":"AvailFinanace",
    "Bid":3,
     "Hiring":"November",
     "Package":"10-15LPA",
     "Difficulty":"Medium",
     "Link":"https://availfinance.in/opportunities/",
  },
  {
    "Name":"ClearTax",
    "Bid":3,
     "Hiring":"November",
     "Package":"15-30LPA",
     "Difficulty":"Medium",
     "Link":"https://cleartax-talent.freshteam.com/jobs?location=[%22Bengaluru,%20India%22]&department=[%223000165743%22]&jobType=[%222%22]&title=&isRemoteLocation=false",
  },
  {
    "Name":"Paytm",
    "Bid":3,
     "Hiring":"November",
     "Package":"10LPA",
     "Difficulty":"Medium",
     "Link":"https://jobs.lever.co/paytm",
  },
  {
    "Name":"Rupeek",
    "Bid":3,
     "Hiring":"November",
     "Package":"20-25LPA",
     "Difficulty":"Medium",
     "Link":"https://rupeek.com/about/careers?city=Bangalore",
  },
  {
    "Name":"Intuit",
    "Bid":4,
     "Hiring":"November",
     "Package":"25-28 LPA",
     "Difficulty":"Medium",
     "Link":"https://jobs.intuit.com/search-jobs/",
  },
  {
    "Name":"MorganStanley",
    "Bid":4,
     "Hiring":"Jan-March",
     "Package":"25 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.morganstanley.com/careers/career-opportunities-search",
  },
  {
    "Name":"FidelityInvestments",
    "Bid":4,
     "Hiring":"November",
     "Package":"10-15 LPA",
     "Difficulty":"Medium",
     "Link":"https://india.fidelity.com/job-details/16282271/data-scientist-senior-data-scientist/",
  },
  {
    "Name":"WellsFargo",
    "Bid":4,
     "Hiring":"November",
     "Package":"12-15 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.wellsfargo.com/about/careers/",
  },
  {
    "Name":"BNYMelon",
    "Bid":4,
     "Hiring":"November",
     "Package":"13 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.bnymellon.com/us/en/careers/students.html",
  },
  {
    "Name":"UBER",
    "Bid":5,
     "Hiring":"Feb-May",
     "Package":"33 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.uber.com/in/en/careers/list/",
  },
  {
    "Name":"Gojek",
    "Bid":5,
     "Hiring":"November",
     "Package":"22 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.gojek.io/careers/all",
  },
  {
    "Name":"OLA",
    "Bid":5,
     "Hiring":"November",
     "Package":"10-15 LPA",
     "Difficulty":"Medium",
     "Link":"https://ola.skillate.com/",
  },
  {
    "Name":"Palo Alto Networks",
    "Bid":6,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://jobs.paloaltonetworks.com/en/",
  },
  {
    "Name":"Intel",
    "Bid":7,
     "Hiring":"November",
     "Package":"15-18 LPA",
     "Difficulty":"Medium",
     "Link":"https://jobs.intel.com/en/search-jobs",
  },
  {
    "Name":"Juniper Networks",
    "Bid":6,
     "Hiring":"November",
     "Package":"15-18 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.juniper.net/#/",
  },
  {
    "Name":"Cisco",
    "Bid":8,
     "Hiring":"November",
     "Package":"15-18 LPA",
     "Difficulty":"Medium",
     "Link":"https://jobs.cisco.com/jobs/SearchJobs/?source=Cisco+Jobs+Career+Site&tags=CDC+Browse+all+jobs+careers",
  },
  {
    "Name":"Western Digitals",
    "Bid":6,
     "Hiring":"November",
     "Package":"20 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.smartrecruiters.com/WesternDigital",
  },
  {
    "Name":"Rubrik",
    "Bid":9,
     "Hiring":"November",
     "Package":"30+ LPA",
     "Difficulty":"Medium",
     "Link":"https://app.ripplematch.com/company/rubrik/#cbp-jobs",
  },
  {
    "Name":"Cohesity",
    "Bid":9,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://careers.cohesity.com/open-positions/",
  },
  {
    "Name":"Tekion Corp",
    "Bid":9,
     "Hiring":"November",
     "Package":"18-20 LPA",
     "Difficulty":"Medium",
     "Link":"https://tekion.com/job-openings/india/all",
  },
  {
    "Name":"Harness",
    "Bid":9,
     "Hiring":"November",
     "Package":"27+ LPA",
     "Difficulty":"Medium",
     "Link":"https://jobs.lever.co/harness",
  },
  {
    "Name":"Nutanix",
    "Bid":9,
     "Hiring":"November",
     "Package":"20-30 LPA",
     "Difficulty":"Medium",
     "Link":"https://nutanix.eightfold.ai/careers?&domain=nutanix.com",
  },
  {
    "Name":"NetApp",
    "Bid":9,
     "Hiring":"November",
     "Package":"15 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.netapp.com/company/careers/",
  },
  {
    "Name":"ServiceNow",
    "Bid":10,
     "Hiring":"November",
     "Package":"21-25 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.servicenow.com/careers/jobs?lang=en-US&locations=Bangalore,Karnataka,%7CDelhi,,&page=1",
  },
  {
    "Name":"ThoughtWorks",
    "Bid":10,
     "Hiring":"November",
     "Package":"9-15 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.thoughtworks.com/en-in/careers",
  },
  {
    "Name":"Citrix",
    "Bid":10,
     "Hiring":"November",
     "Package":"20-25 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.cloud.com/jobs/search?page=1&country_codes%5B%5D=IN&query=",
  },
  {
    "Name":"Postman",
    "Bid":10,
     "Hiring":"November",
     "Package":"10-20 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.postman.com/company/careers/open-positions/",
  },
  {
    "Name":"Airbnb",
    "Bid":11,
     "Hiring":"November",
     "Package":"10 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.airbnb.com/",
  },
  {
    "Name":"Expedia",
    "Bid":11,
     "Hiring":"Jan-Mar",
     "Package":"12-15 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.expediagroup.com/jobs/",
  },
  {
    "Name":"Oyo",
    "Bid":11,
     "Hiring":"November",
     "Package":"10 LPA",
     "Difficulty":"Medium",
     "Link":"http://oyorooms.careersitemanager.com/",
  },
  {
    "Name":"Make My Trip",
    "Bid":11,
     "Hiring":"November",
     "Package":"10-15 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.makemytrip.com/prod/jobs",
  },
  {
    "Name":"Rivigo",
    "Bid":12,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://www.rivigo.com/careers/",
  },
  {
    "Name":"Delhivery",
    "Bid":12,
     "Hiring":"November",
     "Package":"9-10 LPA",
     "Difficulty":"Medium",
     "Link":"https://delhivery.darwinbox.in/ms/candidate/careers",
  },
  {
    "Name":"Turvo Inc.",
    "Bid":12,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://turvo.com/careers/",
  },
  {
    "Name":"Tower Research",
    "Bid":13,
     "Hiring":"November",
     "Package":"45 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.tower-research.com/open-positions",
  },
  {
    "Name":"Graviton Research",
    "Bid":13,
     "Hiring":"November",
     "Package":"25 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.gravitontrading.com/careers.html",
  },
  {
    "Name":"World Quant",
    "Bid":13,
     "Hiring":"November",
     "Package":"40+ LPA",
     "Difficulty":"Medium",
     "Link":"whttps://www.worldquant.com/career-listing/",
  },
  {
    "Name":"Twilio",
    "Bid":14,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://www.twilio.com/company/jobs",
  },
  {
    "Name":"Zoom",
    "Bid":14,
     "Hiring":"November",
     "Package":"12-14 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.zoom.us/jobs/search",
  },
  {
    "Name":"Airtel X Labs",
    "Bid":14,
     "Hiring":"November",
     "Package":"12-15 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.airtel.com/",
  },
  {
    "Name":"Innovacer",
    "Bid":15,
     "Hiring":"November",
     "Package":"12+ LPA",
     "Difficulty":"Medium",
     "Link":"https://career.innovaccer.com/careers/#open-positions",
  },
  {
    "Name":"Flipkart",
    "Bid":2,
     "Hiring":"January",
     "Package":"26 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.flipkartcareers.com/#!/joblist"
  },
  {
    "Name":"Walmart",
    "Bid":2,
     "Hiring":"November",
     "Package":"20-21 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.walmart.com/",
  },
  {
    "Name":"Target",
    "Bid":2,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://india.target.com/careers",
  },
  {
    "Name":"CureFit",
    "Bid":2,
     "Hiring":"November",
     "Package":"20-24 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.cult.fit/careers",
  },
  {
    "Name":"Myntra",
    "Bid":2,
     "Hiring":"November",
     "Package":"24 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.myntra.com/jobs/technology",
  },
  {
    "Name":"Udaan",
    "Bid":2,
     "Hiring":"November",
     "Package":"30-35 LPA",
     "Difficulty":"Medium",
     "Link":"https://udaan.darwinbox.in/ms/candidate/careers",
  },
  {
    "Name":"Rakuten",
    "Bid":2,
     "Hiring":"November",
     "Package":"58 LPA",
     "Difficulty":"Medium",
     "Link":"https://rakuten.openings.co/#!/",
  },
  {
    "Name":"Jupiter Money",
    "Bid":3,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://jobs.lever.co/jupiter",
  },
  {
    "Name":"Juspay",
    "Bid":3,
     "Hiring":"Start Of 4th Year",
     "Package":"25+ LPA",
     "Difficulty":"Medium",
     "Link":"https://juspay.in/careers",
  },
  {
    "Name":"PayPal",
    "Bid":3,
     "Hiring":"November",
     "Package":"20 LPA",
     "Difficulty":"Medium",
     "Link":"https://paypal.eightfold.ai/careers/join?domain=paypal.com",
  },
  {
    "Name":"Visa",
    "Bid":3,
     "Hiring":"November",
     "Package":"15-20 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.visa.co.in/careers.html",
  },
  {
    "Name":"American Express",
    "Bid":3,
     "Hiring":"November",
     "Package":"13 LPA",
     "Difficulty":"Medium",
     "Link":"https://aexp.eightfold.ai/careers?intlink=us-amex-career-en-us-home-findalljobs",
  },
  {
    "Name":"Master Card",
    "Bid":3,
     "Hiring":"November",
     "Package":"12-13 LPA",
     "Difficulty":"Medium",
     "Link":"https://mastercard.jobs/ind/jobs/",
  },
  {
    "Name":"Nasdaq",
    "Bid":3,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://www.nasdaq.com/about/careers",
  },
  {
    "Name":"CRED",
    "Bid":3,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://careers.cred.club/allJob",
  },
  {
    "Name":"DE Shaw",
    "Bid":4,
     "Hiring":"November",
     "Package":"35-37 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.deshawindia.com/careers/faq",
  },
  {
    "Name":"Goldmann Sachs",
    "Bid":4,
     "Hiring":"Jan,Aug",
     "Package":"26-32 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.goldmansachs.com/careers/students/index.html",
  },
  {
    "Name":"Arcesium",
    "Bid":4,
     "Hiring":"November",
     "Package":"30-35 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.arcesium.com/go/All-Jobs/4687610/",
  },
  {
    "Name":"JP Morgan",
    "Bid":4,
     "Hiring":"November",
     "Package":"21 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.jpmorgan.com/IN/en/home",
  },
  {
    "Name":"CitiBank",
    "Bid":4,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://careers.citigroup.com/",
  },
  {
    "Name":"StandardChartered",
    "Bid":4,
     "Hiring":"November",
     "Package":"13 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.sc.com/en/global-careers/early-careers/",
  },
  {
    "Name":"Dunzo",
    "Bid":5,
     "Hiring":"Nov-Dec(Intern)",
     "Package":"20-25 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.dunzo.com/careers#jobs",
  },
  {
    "Name":"Grab",
    "Bid":5,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://grab.careers/",
  },
  {
    "Name":"Directi",
    "Bid":6,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://jobs.lever.co/directi",
  },
  {
    "Name":"Qualcomm",
    "Bid":6,
     "Hiring":"November",
     "Package":"23-24 LPA",
     "Difficulty":"Medium",
     "Link":"https://qualcomm.wd5.myworkdayjobs.com/External",
  },
  {
    "Name":"Samsung",
    "Bid":7,
     "Hiring":"November",
     "Package":"18-24 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.samsung.com/in/about-us/careers/",
  },
  {
    "Name":"Vmware",
    "Bid":7,
     "Hiring":"November",
     "Package":"20-25 LPA",
     "Difficulty":"Medium",
     "Link":"https://careers.vmware.com/main/jobs?page=1",
  },
  {
    "Name":"Nvidia",
    "Bid":7,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
  },
  {
    "Name":"Sharechat",
    "Bid":16,
     "Hiring":"November",
     "Package":"20 LPA",
     "Difficulty":"Medium",
     "Link":"https://sharechat.com/careers",
  },
  {
    "Name":"Bytedance",
    "Bid":16,
     "Hiring":"November",
     "Package":"52 LPA",
     "Difficulty":"Medium",
     "Link":"#",
  },
  {
    "Name":"Hotstar",
    "Bid":16,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://careers.hotstar.com/jobs",
  },
  {
    "Name":"Flock",
    "Bid":16,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://careers.flock.com/",
  },
  {
    "Name":"Inmobi",
    "Bid":16,
     "Hiring":"November",
     "Package":"13-15 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.inmobi.com/company/careers/?country=india",
  },
  {
    "Name":"Atlassian",
    "Bid":10,
     "Hiring":"Post January",
     "Package":"52 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.inmobi.com/company/careers/?country=india",
  },
  {
    "Name":"Sprinkler",
    "Bid":10,
     "Hiring":"November",
     "Package":"18-30 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.inmobi.com/company/careers/?country=india",
  },
  {
    "Name":"AppDynamics",
    "Bid":10,
     "Hiring":"November",
     "Package":"18-30 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.inmobi.com/company/careers/?country=india",
  },
  {
    "Name":"Dream 11",
    "Bid":17,
     "Hiring":"November",
     "Package":"25-30 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.inmobi.com/company/careers/?country=india",
  },
  {
    "Name":"MPL",
    "Bid":17,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://www.inmobi.com/company/careers/?country=india",
  },
  {
    "Name":"Zynga",
    "Bid":16,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://www.inmobi.com/company/careers/?country=india",
  },
  {
    "Name":"Twitter",
    "Bid":14,
     "Hiring":"November",
     "Package":"30 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.inmobi.com/company/careers/?country=india",
  },
  {
    "Name":"Slack",
    "Bid":14,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"https://www.inmobi.com/company/careers/?country=india",
  },
  {
    "Name":"Zomato",
    "Bid":19,
     "Hiring":"November",
     "Package":"19 LPA",
     "Difficulty":"Medium",
     "Link":"https://www.inmobi.com/company/careers/?country=india",
  },
  {
    "Name":"Swiggy",
    "Bid":19,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"YugaByteDB",
    "Bid":20,
     "Hiring":"November",
     "Package":"47 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"MongoDB",
    "Bid":20,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Salesforce",
    "Bid":20,
     "Hiring":"November",
     "Package":"34 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"CodeNation",
    "Bid":21,
     "Hiring":"November",
     "Package":"36 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Media.net",
    "Bid":22,
     "Hiring":"Dec-Jan",
     "Package":"30+ LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Groupon",
    "Bid":23,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Linkedin",
    "Bid":24,
     "Hiring":"November",
     "Package":"43-45 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Practo",
    "Bid":25,
     "Hiring":"November",
     "Package":"15-18 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Gupshup",
    "Bid":25,
     "Hiring":"November",
     "Package":"-",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Grow",
    "Bid":25,
     "Hiring":"November",
     "Package":"36 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"HCL",
    "Bid":26,
     "Hiring":"November",
     "Package":"36 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Google",
    "Bid":1,
     "Hiring":"Random",
     "Package":"50+ LPA",
     "Difficulty":"Hard",
     "Link":"",
  },
  {
    "Name":"Infosys",
    "Bid":26,
     "Hiring":"Feb-May (infitq)",
     "Package":"3.6-9.5 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"TCS",
    "Bid":26,
     "Hiring":"CodeVita & TCS NQT",
     "Package":"3.6-7.2 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Cognizant",
    "Bid":26,
     "Hiring":"August",
     "Package":"4-6 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Netmeds",
    "Bid":16,
     "Hiring":"April",
     "Package":"6-10 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Ericsson",
    "Bid":26,
     "Hiring":"March",
     "Package":"3-5-4.5 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"hashdln",
    "Bid":26,
     "Hiring":"january",
     "Package":"8 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Rakuten",
    "Bid":2,
     "Hiring":"Aug or Jan",
     "Package":"6-10 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Barclays",
    "Bid":4,
     "Hiring":"November",
     "Package":"16-20 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Netflix",
    "Bid":17,
     "Hiring":"November",
     "Package":"36 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"BharatPE",
    "Bid":3,
     "Hiring":"January(intern)",
     "Package":"16 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Accolite",
    "Bid":26,
     "Hiring":"April",
     "Package":"6-8 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Urban Ladders",
    "Bid":25,
     "Hiring":"June or Dec",
     "Package":"12-15 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"HackerEarth",
    "Bid":24,
     "Hiring":"Jun or Dec(Intern)",
     "Package":"14-16 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"HackerRank",
    "Bid":24,
     "Hiring":"Jun or Dec(Intern)",
     "Package":"14-16 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Bank Of America",
    "Bid":4,
     "Hiring":"February",
     "Package":"8.5 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"CodeNation",
    "Bid":24,
     "Hiring":"Jan or April",
     "Package":"14-16 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"MAQ Softwares",
    "Bid":22,
     "Hiring":"March-May",
     "Package":"6-8 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"KickDrum",
    "Bid":4,
     "Hiring":"March",
     "Package":"14-16 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Seekify",
    "Bid":25,
     "Hiring":"October",
     "Package":"10-12 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Cars24",
    "Bid":2,
     "Hiring":"November",
     "Package":"15-16 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Optum",
    "Bid":16,
     "Hiring":"Dare2Compete",
     "Package":"10 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"GeeksForGeeks",
    "Bid":24,
     "Hiring":"Hiring Challenges",
     "Package":"6-8 LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
  {
    "Name":"Amazon",
    "Bid":1,
     "Hiring":"Random",
     "Package":"40+ LPA",
     "Difficulty":"Hard",
     "Link":"",
  },
  {
    "Name":"BrowserStack",
    "Bid":10,
     "Hiring":"Nov-Jan",
     "Package":"25+ LPA",
     "Difficulty":"Medium",
     "Link":"",
  },
]
let businesses=[" ","Big Tech","Ecommerce","Financial Services","Investment Banks","Ride Sharing","Network","Hardware","Software","Cloud Services","DevOps/Software Tools","Travel/Hospitality","Logistics","High Freq Trading","Communication","HealthCare & Fitness","Entertainment","Gaming","Communication","Food Delivery","DataBase/CRM","ITSolutions","Advertisments","Coupons","Job Hunting","Others","Service Based"]
let colors=[" ","#C0EEE4","#F8F988","#FFCAC8","#C147E9","#46C2CB","#3B9AE1","#38E54D","#704F4F","#FF9E9E","#FAAB78","#FAAB78","#B6E2A1","#9ED5C5","#B1AFFF","#A7FFE4","#C689C6","#FFAE6D","#B2C8DF","#D3CEDF","#B8F1B0","#E78EA9","#FFBF86","#C3B091","#00FFAB","#F4EAD5","#FB2576"]
let sno=1;
companies.forEach(tableCreate);


function tableCreate(company) {
    //body reference 
    
  
    // create elements <table> and a <tbody>
    
    var tblbdy=document.getElementById("table1body")
    
      var row = document.createElement("tr");
      row.style.height="50px";
      
        var cell = document.createElement("td");
        var cellText = document.createTextNode(sno);
        sno+=1;
        cell.appendChild(cellText);
        row.appendChild(cell);
        // if(sno%2==0){
        //  cell = document.createElement("td");
        //  var box=document.createElement("div");
        //  box.style.backgroundColor="lightgreen";
        //  box.classList.add("cbox");
        //  cellText = document.createTextNode(company.Name);
        //  box.appendChild(cellText);
        //  cell.appendChild(box);
        //  row.appendChild(cell);
        // }
       
          cell = document.createElement("td");
          var box=document.createElement("div");
          box.style.backgroundColor=colors[company.Bid];
          box.classList.add("cbox");

          cellText = document.createTextNode(company.Name);
          box.appendChild(cellText);
          cell.appendChild(box);
          row.appendChild(cell);
        
        cell = document.createElement("td");
        cellText = document.createTextNode(businesses[company.Bid]);
        cell.appendChild(cellText);
        row.appendChild(cell);

        cell = document.createElement("td");
        cellText = document.createTextNode(company.Hiring);
        cell.appendChild(cellText);
        row.appendChild(cell);

        cell = document.createElement("td");
        cellText = document.createTextNode(company.Package);
        cell.appendChild(cellText);
        row.appendChild(cell);

        cell = document.createElement("td");
        cellText = document.createTextNode(company.Difficulty);
        cell.appendChild(cellText);
        row.appendChild(cell);

        cell = document.createElement("td");
        var link = document.createElement("a");
        link.setAttribute('href',company.Link);
        link.text="Apply Here";
        cell.appendChild(link);
        row.appendChild(cell);

      tblbdy.appendChild(row);
  }

  function openForm() {
    document.getElementById("myForm").style.display = "block";
  }
  
  function closeForm() {
    document.getElementById("myForm").style.display = "none";
  }